services:
  portal:
    image: crpi-7st94yd1uskrhjrz.cn-chengdu.personal.cr.aliyuncs.com/seclabx/seclabx-web-portal:latest
    container_name: seclabx-web-portal
    ports:
      - "${HOST_IP:-0.0.0.0}:8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
    restart: always
