services:
  portal:
    image: crpi-7st94yd1uskrhjrz.cn-chengdu.personal.cr.aliyuncs.com/seclabx/seclabx-portal:latest
    container_name: seclabx-portal
    ports:
      - "8080:80"
    environment:
      SERVER_NAME: ${SERVER_NAME:-_}
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
    restart: always
