name: Build & Deploy SeclabX Portal

on:
  push:
    branches:
      - main   # 只要推送 main 分支就触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Alibaba Cloud Registry
        run: |
          echo "${{ secrets.ALIYUN_PASSWORD }}" | docker login \
            -u "${{ secrets.ALIYUN_USERNAME }}" \
            --password-stdin crpi-7st94yd1uskrhjrz.cn-chengdu.personal.cr.aliyuncs.com

      - name: Build Docker Image
        run: |
          docker build -t seclabx-web-portal:latest .

      - name: Tag Image
        run: |
          docker tag seclabx-web-portal:latest \
          crpi-7st94yd1uskrhjrz.cn-chengdu.personal.cr.aliyuncs.com/seclabx/seclabx-web-portal:latest

      - name: Push Image
        run: |
          docker push \
          crpi-7st94yd1uskrhjrz.cn-chengdu.personal.cr.aliyuncs.com/seclabx/seclabx-web-portal:latest
